# Generated by Django 5.0.4 on 2024-04-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'can read all books')]},
        ),
    ]
